version: "3.9"

services:
  master:
    container_name: master
    hostname: master
    build:
      context: ./master
    environment:
      REMOTE_HOSTS: "foo-web0"
    env_file:
      - ./variables-agent.env
  foo-web0:
    container_name: foo-web0
    hostname: foo-web0
    build:
      context: ./agent
    environment:
      SUDOERS: "true"
    env_file:
      - ./variables-agent.env