version: "3.9"

services:
  master:
    container_name: master
    hostname: master
    build:
      context: ./master
    environment:
      REMOTE_HOSTS: "web0 web1 app0 app1 db0 db1"
      REMOTE_PASS: "ansible"
  web0:
    container_name: web0
    hostname: web0
    build:
      context: ./agent
    environment:
      USER_PASS: "ansible"
  web1:
    container_name: web1
    hostname: web1
    build:
      context: ./agent
    environment:
      USER_PASS: "ansible"
  app0:
    container_name: app0
    hostname: app0
    build:
      context: ./agent
    environment:
      USER_PASS: "ansible"
  app1:
    container_name: app1
    hostname: app1
    build:
      context: ./agent
    environment:
      USER_PASS: "ansible"
  db0:
    container_name: db0
    hostname: db0
    build:
      context: ./agent
    environment:
      USER_PASS: "ansible"
  db1:
    container_name: db1
    hostname: db1
    build:
      context: ./agent
    environment:
      USER_PASS: "ansible"