---
- name: Create '/tmp/foo'
  file:
    path: /tmp/foo
    state: directory
    mode: '0755'
  tags: [ foo ]
- name: Create '/tmp/bar'
  file:
    path: /tmp/bar
    state: directory
    mode: '0755'
  tags: [ bar ]
- name: Create '/tmp/baz'
  file:
    path: /tmp/baz
    state: directory
    mode: '0755'
  tags: [ baz ]